# Generated by Django 3.0.6 on 2020-05-22 10:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import main.otherFunctions.listField
import main.storage


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('name', models.CharField(max_length=150, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Img',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('image', models.ImageField(null=True, storage=main.storage.ImageStorage(), upload_to='img')),
                ('cmpScore', models.FloatField(null=True)),
                ('like', models.IntegerField(null=True)),
                ('description', models.TextField(null=True)),
                ('createTime', models.DateTimeField(auto_now=True)),
                ('label', main.otherFunctions.listField.ListField(null=True, token=',')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imgs', to=settings.AUTH_USER_MODEL)),
                ('tagClass', models.ManyToManyField(related_name='imgs', to='main.Classification')),
                ('userLike', models.ManyToManyField(related_name='likeimgs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=30, null=True)),
                ('proPicture', models.ImageField(null=True, storage=main.storage.ImageStorage(), upload_to='img')),
                ('biography', models.TextField(null=True)),
                ('historyImgs', models.ManyToManyField(related_name='viewed_users', to='main.Img')),
                ('userProfile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userprofile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('createTime', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
                ('img', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='main.Img')),
            ],
        ),
    ]
